sed -i "s/archive.ubuntu/mirrors.aliyun/g" /etc/apt/sources.list
apt-get update
apt-get install -y software-properties-common python-software-properties
add-apt-repository -y ppa:ondrej/php
apt-get update
apt-get install -y php5.6-fpm php5.6-mysql php5.6-apcu php5.6-imagick php5.6-imap php5.6-intl php5.6-mcrypt php5.6-gd php5.6-memcache php5.6-memcached php5.6-curl esmtp esmtp-run